# Spring Boot configuration
spring:

  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gateways_devices
    username: root
    password: root
    max-active: 5
    max-idle: 4
    min-idle: 4
    max-wait: 10000
    min-evictable-idle-time-millis: 1000

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true

  # Flyway configuration
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: gateways_devices
    user: root
    password: root
    baseline-on-migrate: true
    baseline-version: 1

  # Logger configuration
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

# Server configuration
server:
  port: 8080